language: python

python:
  - 2.7
  - 3.4

install:
  - pip install -r requirements.txt
  - wget https://repo1.maven.org/maven2/org/openprovenance/prov/toolbox/0.7.1/toolbox-0.7.1-release.zip
  - unzip toolbox-0.7.1-release.zip
  - export PATH=$PATH:$PWD/ProvToolbox/bin/
script:
  - nosetests -v --nocapture prov_interop/tests
